// core/hcl.js — Reconstructed Terraform HCL blocks from plan expressions
import { escapeHtml } from "./util.js";

/* ---- Terraform block, rebuilt from configuration.expressions. The plan does
   not carry source text, so interpolated values are shown resolved with the
   reference noted alongside. ---- */

function hclLit(v, ind){
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)){
    if (!v.length) return "[]";
    var simple = v.every(function(x){ return typeof x !== "object" || x === null; });
    if (simple) return "[" + v.map(function(x){ return hclLit(x, ind); }).join(", ") + "]";
    return "[\n" + v.map(function(x){ return ind + "  " + hclLit(x, ind + "  "); }).join(",\n") + "\n" + ind + "]";
  }
  var ks = Object.keys(v);
  if (!ks.length) return "{}";
  return "{\n" + ks.map(function(k){
    return ind + "  " + k + " = " + hclLit(v[k], ind + "  ");
  }).join("\n") + "\n" + ind + "}";
}

function isBlockList(v){
  return Array.isArray(v) && v.length > 0 && v.every(function(x){
    return x && typeof x === "object" && !Array.isArray(x);
  });
}

/* plural id/arn/cidr attributes are lists even when the plan cannot resolve
   them yet, so a reference feeding one keeps its brackets */
var LIST_ATTR = /(_ids|_arns|_blocks|_groups|_zones|_subnets|_names)$/;

function exprVal(e, resolved, ind, key){
  if (e && Object.prototype.hasOwnProperty.call(e, "constant_value")) return {txt:hclLit(e.constant_value, ind)};
  if (e && e.references && e.references.length){
    var refs = e.references;
    var direct = refs.filter(function(x){ return /^(aws_|data\.)/.test(x); });
    if (direct.length && refs.length <= 2){
      /* a reference feeding a list attribute keeps its brackets */
      var isList = Array.isArray(resolved) || (key && LIST_ATTR.test(key));
      var txt = isList ? "[" + direct[0] + "]" : direct[0];
      return {txt:txt};
    }
    if (resolved !== undefined && resolved !== null)
      return {txt:hclLit(resolved, ind), note:refs.join(", ")};
    return {txt:refs[0]};
  }
  if (resolved !== undefined && resolved !== null) return {txt:hclLit(resolved, ind)};
  return {txt:"null"};
}

function hclFor(r, cfg){
  if (!cfg || !cfg.expressions) return null;
  var L = [];
  L.push('resource "' + r.type + '" "' + r.name + '" {');

  ["count","for_each","provider"].forEach(function(m){
    if (cfg[m] !== undefined){
      var v = exprVal(cfg[m], undefined, "  ", m);
      L.push("  " + m + " = " + v.txt);
    }
  });

  var keys = Object.keys(cfg.expressions).sort();
  var blocks = [];
  keys.forEach(function(k){
    var e = cfg.expressions[k];
    /* terraform encodes a repeated nested block either as an array of
       expression maps, or as one constant_value holding an array of objects */
    if (Array.isArray(e)){ blocks.push({k:k, items:e, wrapped:true}); return; }
    if (e && isBlockList(e.constant_value)){ blocks.push({k:k, items:e.constant_value, wrapped:false}); return; }
    var v = exprVal(e, r.attrs ? r.attrs[k] : undefined, "  ", k);
    L.push("  " + k + " = " + v.txt + (v.note ? "  # from " + v.note : ""));
  });

  blocks.forEach(function(b){
    b.items.forEach(function(item){
      L.push("");
      L.push("  " + b.k + " {");
      Object.keys(item).sort().forEach(function(kk){
        var raw = item[kk];
        if (raw === null || raw === undefined) return;
        var v = b.wrapped ? exprVal(raw, undefined, "    ", kk)
                          : {txt: hclLit(raw, "    ")};
        if (v.txt === "null") return;
        L.push("    " + kk + " = " + v.txt);
      });
      L.push("  }");
    });
  });

  if (cfg.depends_on && cfg.depends_on.length){
    L.push("");
    L.push("  depends_on = [" + cfg.depends_on.join(", ") + "]");
  }

  L.push("}");
  return L.join("\n");
}

/* Syntax colouring for the block above. The HCL is generated by hclFor, so
   its shape is known and a line-based pass is enough: no parser needed. */

function hclValue(v){
  var out = "", re = /("(?:[^"\\]|\\.)*")|\b(true|false|null)\b|(-?\d+(?:\.\d+)?)\b|([A-Za-z_][\w-]*(?:\.[\w-]+)+)/g;
  var last = 0, m;
  while ((m = re.exec(v)) !== null){
    out += escapeHtml(v.slice(last, m.index));
    if (m[1])      out += '<span class="s">' + escapeHtml(m[1]) + '</span>';
    else if (m[2]) out += '<span class="b">' + escapeHtml(m[2]) + '</span>';
    else if (m[3]) out += '<span class="n">' + escapeHtml(m[3]) + '</span>';
    else           out += '<span class="r">' + escapeHtml(m[4]) + '</span>';
    last = m.index + m[0].length;
  }
  return out + escapeHtml(v.slice(last));
}

function hclHighlight(src){
  return src.split("\n").map(function(line){
    /* a trailing "# from ..." note is a comment, whatever precedes it */
    var note = "", hash = line.indexOf("  # ");
    if (hash >= 0){
      note = '<span class="c">' + escapeHtml(line.slice(hash)) + '</span>';
      line = line.slice(0, hash);
    }

    var m;
    if ((m = line.match(/^(resource|data|variable|output|module)\s+("[^"]*")\s+("[^"]*")(\s*\{)$/))){
      return '<span class="k">' + m[1] + '</span> <span class="t">' + escapeHtml(m[2]) +
             '</span> <span class="s">' + escapeHtml(m[3]) + '</span>' + escapeHtml(m[4]) + note;
    }
    if ((m = line.match(/^(\s*)([\w-]+)(\s*=\s*)(.*)$/))){
      return m[1] + '<span class="a">' + escapeHtml(m[2]) + '</span>' +
             escapeHtml(m[3]) + hclValue(m[4]) + note;
    }
    if ((m = line.match(/^(\s*)([\w-]+)(\s*\{)$/))){
      return m[1] + '<span class="k">' + escapeHtml(m[2]) + '</span>' + escapeHtml(m[3]) + note;
    }
    return escapeHtml(line) + note;
  }).join("\n");
}

export { hclLit, isBlockList, exprVal, hclFor, hclValue, hclHighlight };
